from typing import Protocol, runtime_checkable


@runtime_checkable
class AgentPort(Protocol):
    """
    Protocol interface for strategic agents.
    Any agent must implement the `run` method, which takes input content
    and returns a processed output string.
    """

    async def run(self, content: str) -> str:
        """
        Execute the agent logic.

        Parameters
        ----------
        content : str
            Input content (e.g., XML or text) to be processed by the agent.

        Returns
        -------
        str
            Output generated by the agent (e.g., tagged XML, diagram, matrix).
        """
        ...
