from dataclasses import dataclass, field
from typing import Any

from domain.models.enums import StopReason
from domain.models.llm_provider_model import ToolCall


@dataclass
class StateUpdate:
    """A partial state update generated by an agent node."""
    folder_path: str = ""
    content: str = ""
    next_agent: str | None = None
    next_task: str | None = None
    current_file: str | None = None
    stop_reason: StopReason = StopReason.CALL
    task_result: str = ""
    error_message: str | None = None
    final_response: str | None = None
    iteration: int = 0
    metadata: Any = None


@dataclass
class StateMetadata:
    """Consolidated metadata for performance tracking and observability."""

    # Tokens & Usage
    input_tokens: int = 0
    output_tokens: int = 0
    token_usage: int = 0

    # Latencies (ms)
    total_duration_ms: float = 0.0
    load_duration_ms: float = 0.0
    prompt_eval_duration_ms: float = 0.0
    eval_duration_ms: float = 0.0

    # Tracing & Context
    model_name: str | None = None
    last_agent_key: str | None = None
    trace_id: str | None = None
    
    # Task tracking for persistent state
    completed_tasks: list[str] = field(default_factory=list)


@dataclass
class AgentState:
    """The unique source of truth for the Orchestrator workflow."""
    folder_path: str
    user_prompt: str
    content: str = ""
    current_file: str | None = None
    task_result: str = ""
    iteration: int = 0
    next_task: str | None = None
    next_agent: str | None = None
    stop_reason: StopReason = StopReason.CALL
    error_message: str | None = None
    final_response: str | None = None
    
    # LangGraph task management
    task_queue: list[str] = field(default_factory=list)
    metadata: StateMetadata = field(default_factory=StateMetadata)
    
    def update(self, delta: dict | StateUpdate):
        """Merges dictionary or StateUpdate into state."""
        data = delta if isinstance(delta, dict) else delta.__dict__
        for k, v in data.items():
            if hasattr(self, k):
                setattr(self, k, v)


@dataclass
class AgentConfig:
    """Configuration settings for an individual agent instance."""
    agent_id: str
    system_prompt: str
    llm_provider: Any
